// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/Playbill.tsx": () => import("../components/mockups/home-redesign/Playbill.tsx"),
  "./components/mockups/home-redesign/Sentence.tsx": () => import("../components/mockups/home-redesign/Sentence.tsx"),
  "./components/mockups/home-redesign/SwipeDeck.tsx": () => import("../components/mockups/home-redesign/SwipeDeck.tsx")
};
